import Head from 'next/head'
import Image from 'next/image'
import Layout from '../Layout'

export default function Home() {
	return (
		<>
			<Head>
				<title>Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>

				<div className="relative flex flex-col justify-center py-16 sm:py-24 bg-radial-at-t from-indigo-900/40 via-slate-900/50 to-slate-900 h-screen">
						<main className="mx-auto max-w-7xl px-4">
							<div className="text-center">
								<h1 className="mt-0 lg:mt-7 text-4xl text-gray-900 dark:text-gray-100 sm:text-5xl md:text-6xl xl:text-8xl 2xl:text-9xl">
									<span className="block font-black tracking-tighter text-gradient bg-gradient-to-b from-indigo-700 via-indigo-200 to-indigo-700 xl:inline">Frontend, Backend Developer</span>
								</h1>
								<p className="mt-3 max-w-md mx-auto text-base text-slate-400 sm:text-lg md:mt-16 md:text-xl xl:text-2xl 2xl:text-3xl md:max-w-3xl">
									Hi! 👋🏼 My name is Miftah. I'm a enthusiast of codes whenever and wherever, curiosity and the urge of being good at something is always a motivation.
								</p>
								<div className="mt-5 max-w-md mx-auto sm:flex sm:justify-center md:mt-16">
												
								<a href="#_" className="mt-10 sm:mt-0 box-border relative z-10 inline-flex items-center justify-center w-auto px-12 py-3 overflow-hidden font-bold text-white transition-all duration-300 bg-indigo-600 rounded-xl cursor-pointer group ring-offset-4 ring-2 ring-offset-slate-800 ring-indigo-800 hover:ring-offset-indigo-800 ease focus:outline-none">
									<span className="absolute bottom-0 right-0 w-8 h-20 -mb-8 -mr-5 transition-all duration-300 ease-out transform rotate-45 translate-x-1 bg-indigo-900/30 group-hover:-translate-x-7 group-hover:bg-indigo-900 group-hover:scale-150 group-hover:h-44 group-hover:w-12"></span>
									<span className="absolute top-0 left-0 w-20 h-8 -mt-1 -ml-12 transition-all duration-300 ease-out transform group-hover:bg-indigo-900 -rotate-45 -translate-x-1 bg-indigo-900/30 group-hover:translate-x-10 group-hover:scale-150 group-hover:h-12 group-hover:w-36"></span>
									<span className="relative z-20 flex items-center text-base md:text-xl">Get in touch</span>
								</a>
									<div className="mt-10 sm:mt-0 sm:ml-3">
											<a href="https://marcreichel.dev/open-source"
												className="w-full flex items-center justify-center px-8 py-3 border border-transparent text-base font-medium rounded-md text-white bg-transparent hover:underline hover:underline-offset-8 hover:decoration-4 hover:decoration-indigo-500 md:py-4 md:text-xl md:px-10">
													or learn more
											</a>
									</div>
								</div>
							</div>
						</main>
				</div>
				<div className="relative py-16 sm:py-24 bg-slate-900/70">
					<main className="mx-auto max-w-7xl px-4">
						<div className="text-center">
						<h2 className="h-15 text-4xl font-semibold text-slate-100 underline underline-offset-8 decoration-indigo-500 decoration-4">Latest Work</h2>
						<div className="mt-20 p-2 font-inter grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-16">
							<div className="group relative bg-slate-900 border-4 border-indigo-900 aspect-square shadow-lg rounded-3xl text-slate-100 p-5 cursor-pointer">
								<div className="relative w-full h-1/2 overflow-hidden">
									<div className="absolute inset-0 group-hover:scale-105 transition-all duration-500 w-full h-full bg-[url('/laptop-1.jpg')] rounded-3xl bg-center bg-cover"/>
								</div>
								<main className="mt-8 w-full">
									<h4 className="text-2xl text-left group-hover:underline group-hover:underline-offset-8 group-hover:text-indigo-400 group-hover:transition-color group-hover:duration-500 font-bold">My Sunplan</h4>
									<span className="mt-3 mb-5 block text-xl text-justify text-slate-300">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquid non repellendus amet, mollitia quod necessitatibus tenetur dignissimos reprehenderit odit fugiat asperiores, dicta, alias quaerat quidem similique eum laudantium laborum unde? Lorem ipsum dolor sitlorem?</span>
								</main>
								<div className="absolute flex justify-center inset-x-0 -bottom-10 w-full">
									<div className='w-1/2 border-4 border-indigo-900 bg-slate-900 rounded-2xl'>
										<div className="p-2 inline-flex"><Image src={"/codeigniter-logo.svg"} width={50} height={50} /></div>
										<div className="p-2 inline-flex"><Image src={"/laravel-logo.svg"} width={80} height={50} /></div>
									</div>
								</div>
							</div>
							<div className="group relative bg-slate-900 border-4 border-indigo-900 aspect-square shadow-lg rounded-3xl text-slate-100 p-5 cursor-pointer">
								<div className="relative w-full h-1/2 overflow-hidden">
									<div className="absolute inset-0 group-hover:scale-105 transition-all duration-500 w-full h-full bg-[url('/laptop-1.jpg')] rounded-3xl bg-center bg-cover"/>
								</div>
								<main className="mt-8 w-full">
									<h4 className="text-2xl text-left group-hover:underline group-hover:underline-offset-8 group-hover:text-indigo-400 group-hover:transition-color group-hover:duration-500 font-bold">My Sunplan</h4>
									<span className="mt-3 mb-5 block text-xl text-justify text-slate-300">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquid non repellendus amet, mollitia quod necessitatibus tenetur dignissimos reprehenderit odit fugiat asperiores, dicta, alias quaerat quidem similique eum laudantium laborum unde? Lorem ipsum dolor sitlorem?</span>
								</main>
								<div className="absolute flex justify-center inset-x-0 -bottom-10 w-full">
									<div className='w-1/2 border-4 border-indigo-900 bg-slate-900 rounded-2xl'>
										<div className="p-2 inline-flex"><Image src={"/codeigniter-logo.svg"} width={50} height={50} /></div>
										<div className="p-2 inline-flex"><Image src={"/laravel-logo.svg"} width={80} height={50} /></div>
									</div>
								</div>
							</div>
							<div className="group relative bg-slate-900 border-4 border-indigo-900 aspect-square shadow-lg rounded-3xl text-slate-100 p-5 cursor-pointer">
								<div className="relative w-full h-1/2 overflow-hidden">
									<div className="absolute inset-0 group-hover:scale-105 transition-all duration-500 w-full h-full bg-[url('/laptop-1.jpg')] rounded-3xl bg-center bg-cover"/>
								</div>
								<main className="mt-8 w-full">
									<h4 className="text-2xl text-left group-hover:underline group-hover:underline-offset-8 group-hover:text-indigo-400 group-hover:transition-color group-hover:duration-500 font-bold">My Sunplan</h4>
									<span className="mt-3 mb-5 block text-xl text-justify text-slate-300">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquid non repellendus amet, mollitia quod necessitatibus tenetur dignissimos reprehenderit odit fugiat asperiores, dicta, alias quaerat quidem similique eum laudantium laborum unde? Lorem ipsum dolor sitlorem?</span>
								</main>
								<div className="absolute flex justify-center inset-x-0 -bottom-10 w-full">
									<div className='w-1/2 border-4 border-indigo-900 bg-slate-900 rounded-2xl'>
										<div className="p-2 inline-flex"><Image src={"/codeigniter-logo.svg"} width={50} height={50} /></div>
										<div className="p-2 inline-flex"><Image src={"/laravel-logo.svg"} width={80} height={50} /></div>
									</div>
								</div>
							</div>
							<div className="group relative bg-slate-900 border-4 border-indigo-900 aspect-square shadow-lg rounded-3xl text-slate-100 p-5 cursor-pointer">
								<div className="relative w-full h-1/2 overflow-hidden">
									<div className="absolute inset-0 group-hover:scale-105 transition-all duration-500 w-full h-full bg-[url('/laptop-1.jpg')] rounded-3xl bg-center bg-cover"/>
								</div>
								<main className="mt-8 w-full">
									<h4 className="text-2xl text-left group-hover:underline group-hover:underline-offset-8 group-hover:text-indigo-400 group-hover:transition-color group-hover:duration-500 font-bold">My Sunplan</h4>
									<span className="mt-3 mb-5 block text-xl text-justify text-slate-300">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquid non repellendus amet, mollitia quod necessitatibus tenetur dignissimos reprehenderit odit fugiat asperiores, dicta, alias quaerat quidem similique eum laudantium laborum unde? Lorem ipsum dolor sitlorem?</span>
								</main>
								<div className="absolute flex justify-center inset-x-0 -bottom-10 w-full">
									<div className='w-1/2 border-4 border-indigo-900 bg-slate-900 rounded-2xl'>
										<div className="p-2 inline-flex"><Image src={"/codeigniter-logo.svg"} width={50} height={50} /></div>
										<div className="p-2 inline-flex"><Image src={"/laravel-logo.svg"} width={80} height={50} /></div>
									</div>
								</div>
							</div>
						</div>
						</div>
					</main>
				</div>
				<div className="relative py-16 sm:py-24 bg-gradient-to-b from-slate-900/80 to-indigo-900/50">
					<main className="mx-auto max-w-7xl px-4">
						<div className="text-center">
							<h2 className="h-15 text-4xl font-semibold text-slate-100 underline underline-offset-8 decoration-indigo-500 decoration-4">Very Clear Process</h2>
							<ol className="mt-24 border-l-4 mx-5 md:mx-0 md:border-l-0 md:border-t-4 border-indigo-900 md:flex md:justify-center md:gap-6">
								<li className="block text-left md:w-1/4">
									<div className="flex md:block flex-start items-center pt-2 md:pt-0">
									<div className="flex z-10 justify-center items-center w-9 h-9 bg-indigo-900 rounded-full ring-0 ring-indigo-900 sm:ring-8 shrink-0 -ml-5 md:-ml-0 -mt-6">
										<svg className="w-9 h-9 text-slate-200" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path></svg>
									</div>
									</div>
									<div className="mt-10 ml-4 md:ml-0 pb-5">
										<h4 className="text-slate-100 font-semibold text-2xl mb-5">Analysis</h4>
										<p className="text-slate-300 text-xl mb-3">Langkah Awal adalah memahami cara kerja bagian dalam model bisnis anda secara mendetail.</p>
									</div>
								</li>
								<li className="block text-left md:w-1/4">
									<div className="flex md:block flex-start items-center pt-2 md:pt-0">
									<div className="flex z-10 justify-center items-center w-9 h-9 bg-indigo-900 rounded-full ring-0 ring-indigo-900 sm:ring-8 shrink-0 -ml-5 md:-ml-0 -mt-6">
										<svg className="w-9 h-9 text-slate-200" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path></svg>
									</div>
									</div>
									<div className="mt-10 ml-4 md:ml-0 pb-5">
										<h4 className="text-slate-100 font-semibold text-2xl mb-5">Plan</h4>
										<p className="text-slate-300 text-xl mb-3">Merencanakan dengan cara memprioritaskan fitur utama berdasarkan perkiraan waktu sesuai kebutuhan bisnis anda.</p>
									</div>
								</li>
								<li className="block text-left  md:w-1/4">
									<div className="flex md:block flex-start items-center pt-2 md:pt-0">
									<div className="flex z-10 justify-center items-center w-9 h-9 bg-indigo-900 rounded-full ring-0 ring-indigo-900 sm:ring-8 shrink-0 -ml-5 md:-ml-0 -mt-6">
										<svg className="w-9 h-9 text-slate-200" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path></svg>
									</div>
									</div>
									<div className="mt-10 ml-4 md:ml-0 pb-5">
										<h4 className="text-slate-100 font-semibold text-2xl mb-5">Build</h4>
										<p className="text-slate-300 text-xl mb-3">Melalui sistem pengiriman berkelanjutan dan jaminan kualitas agar membuat anda tetap up to date selama proses pengembangan dan memastikan anda puas dan bahwa masalah dapat diperbaiki sebelum di perkenalkan ke produk akhir.</p>
									</div>
								</li>
								<li className="block text-left md:w-1/4">
									<div className="flex md:block flex-start items-center pt-2 md:pt-0">
									<div className="flex z-10 justify-center items-center w-9 h-9 bg-indigo-900 rounded-full ring-0 ring-indigo-900 sm:ring-8 shrink-0 -ml-5 md:-ml-0 -mt-6">
										<svg className="w-9 h-9 text-slate-200" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fillRule="evenodd" d="M6 2a1 1 0 00-1 1v1H4a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V6a2 2 0 00-2-2h-1V3a1 1 0 10-2 0v1H7V3a1 1 0 00-1-1zm0 5a1 1 0 000 2h8a1 1 0 100-2H6z" clipRule="evenodd"></path></svg>
									</div>
									</div>
									<div className="mt-10 ml-4 md:ml-0 pb-5">
										<h4 className="text-slate-100 font-semibold text-2xl mb-5">Maintenance</h4>
										<p className="text-slate-300 text-xl mb-3">Kode yang dipikirkan dengan baik mempermudah untuk di pelihara dengan biaya rendah, melalui pemantauan memastikan aplikasi tetap sehat, sehingga anda dapat fokus pada hal-hal penting.</p>
									</div>
								</li>

							</ol>
						</div>
					</main>
				</div>

				<div className="relative py-16 sm:py-24 bg-gradient-to-t from-slate-900/80 to-indigo-900/50">
					<main className="mx-auto max-w-3xl px-4">
						<h2 className="h-15 text-4xl font-semibold text-slate-100 underline underline-offset-8 decoration-indigo-500 decoration-4 text-center mb-16">Latest Posts</h2>
						<div className="w-full divide-y-2 divide-indigo-500">
							<div className="h-15 w-full px-2 py-10">
								<h4 className="text-2xl font-bold mb-2 text-slate-100">Membuat Kartu Nama</h4>
								<p className="mb-5 text-indigo-200">27 November 1995</p>
								<main className="w-full text-left">
									<span className="text-slate-300 text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda, saepe cupiditate eius, magni temporibus est molestiae aperiam atque quaerat eligendi vero maxime debitis excepturi cum officia? Quaerat, eos dolore!</span>
								</main>
							</div>
							<div className="h-15 w-full px-2 py-10">
								<h4 className="text-2xl font-bold mb-2 text-slate-100">Membuat Kartu Nama</h4>
								<p className="mb-5 text-indigo-200">27 November 1995</p>
								<main className="w-full text-left">
									<span className="text-slate-300 text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda, saepe cupiditate eius, magni temporibus est molestiae aperiam atque quaerat eligendi vero maxime debitis excepturi cum officia? Quaerat, eos dolore!</span>
								</main>
							</div>
							<div className="h-15 w-full px-2 py-10">
								<h4 className="text-2xl font-bold mb-2 text-slate-100">Membuat Kartu Nama</h4>
								<p className="mb-5 text-indigo-200">27 November 1995</p>
								<main className="w-full text-left">
									<span className="text-slate-300 text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda, saepe cupiditate eius, magni temporibus est molestiae aperiam atque quaerat eligendi vero maxime debitis excepturi cum officia? Quaerat, eos dolore!</span>
								</main>
							</div>
							<div className="h-15 w-full px-2 py-10">
								<h4 className="text-2xl font-bold mb-2 text-slate-100">Membuat Kartu Nama</h4>
								<p className="mb-5 text-indigo-200">27 November 1995</p>
								<main className="w-full text-left">
									<span className="text-slate-300 text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda, saepe cupiditate eius, magni temporibus est molestiae aperiam atque quaerat eligendi vero maxime debitis excepturi cum officia? Quaerat, eos dolore!</span>
								</main>
							</div>
							<div className="h-15 w-full px-2 py-10">
								<h4 className="text-2xl font-bold mb-2 text-slate-100">Membuat Kartu Nama</h4>
								<p className="mb-5 text-indigo-200">27 November 1995</p>
								<main className="w-full text-left">
									<span className="text-slate-300 text-xl">Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem assumenda, saepe cupiditate eius, magni temporibus est molestiae aperiam atque quaerat eligendi vero maxime debitis excepturi cum officia? Quaerat, eos dolore!</span>
								</main>
							</div>
						</div>
					</main>
				</div>
			</Layout>
		</>
	)
}
